spring:
  # ==========================================
  # POSTGRESQL (Banco Relacional - Autenticação e Configurações)
  # ==========================================
  datasource:
    url: jdbc:postgresql://localhost:5432/quale_postgres_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # ==========================================
  # MONGODB (Banco Não Relacional - Chat, Mensagens, Grupos)
  # ==========================================
  data:
    mongodb:
      # Atenção: ?authSource=admin é obrigatório ao usar autenticação no Docker
      uri: mongodb://admin:admin@localhost:27017/quale_mongo_db?authSource=admin

# ==========================================
# LOGS E DEBUG
# ==========================================
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG # Para ver as queries do Mongo no console

# ==========================================
# SWAGGER (OpenAPI)
# ==========================================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html