server :
  port: 8080

# ==========================================
# CONFIGURAÇÕES PERSONALIZADAS DA APLICAÇÃO
# ==========================================
quale:
  upload-dir: ./uploads

spring:
  # ===========================================
  # POSTGRESQL (Banco Relacional - Autenticação e Configurações)
  # ===========================================
  datasource:
    url: jdbc:postgresql://postgres:5432/quale_postgres_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # ==========================================
  # UPLOAD DE ARQUIVOS
  # ==========================================
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  # ==========================================
  # MONGODB (Banco Não Relacional - Chat, Mensagens, Grupos)
  # ==========================================
  mongodb:
    host: mongo
    port: 27017
    database: quale_mongo_db
    uri: mongodb://admin:admin@mongo:27017/quale_mongo_db?authSource=admin

# ==========================================
# SWAGGER (OpenAPI)
# ==========================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs